
language: python

addons:
  postgresq: "9.4"

before_install:
  - sudo apt-get update
  - sudo service postgresql stop
  - sudo service postgresql start 9.4
  - sudo apt-get -y install chkconfig apache2 postgresql-9.4 ssl-cert libapache2-mod-wsgi python python-psycopg2 python-dateutil python-webpy python-tz
  - cd ..
  - git clone https://github.com/informatics-isi-edu/webauthn.git
  - cd webauthn
  - sudo make install PLATFORM=ubuntu1204
  - cd ../hatrac

install:
  - sudo python ./setup.py install

before_script:
  - createdb hatrac_test
  - cp test/hatrac_config.json ~/

script:
  - sudo -u $USER python test/smoketest.py

