
language: python

sudo: required
dist: xenial

python:
  - "3.5"

virtualenv:
  system_site_packages: true

services:
  - postgresql

addons:
  postgresql: "10"
  apt:
    packages:
      - libpq-dev
      - libjson-c-dev
      - postgresql-10
      - postgresql-client-10
      - postgresql-server-dev-10
      - apache2
      - apache2-dev
      - ssl-cert
      - libapache2-mod-wsgi-py3
      - python3-pip
      - python3-setuptools

env:
  global:
    - COOKIES=~/cookies
    - VERBOSE=brief
    - HTTPD_ERROR_LOG=/var/log/apache2/error.log
    - PYTHONWARNINGS="ignore:Unverified HTTPS request"

before_install:
  - sudo su -c 'echo /usr/lib/python3.5/site-packages > /usr/local/lib/python3.5/dist-packages/sys-site-packages.pth'
  - sudo ln -s /etc/apache2/conf-enabled /etc/apache2/conf.d
  - sudo service postgresql stop
  - sudo service postgresql start 10
  - sudo a2enmod ssl
  - sudo a2ensite default-ssl
  - sudo groupadd -o -g $(id -g www-data) apache
  - sudo pip3 install psycopg2-binary
  - sudo pip3 install git+https://github.com/informatics-isi-edu/webpy.git
  - sudo useradd -m -r webauthn
  - sudo su -c '/usr/bin/python3 -c "import sys;import pprint;pprint.pprint(sys.path)"' - webauthn
  - cd ..
  - git clone https://github.com/informatics-isi-edu/webauthn.git
  - cd webauthn
  - git checkout origin/master
  - sudo make install
  - sudo make deploy
  - sudo bash ./test/ubuntu-travis-setup.sh
  - sudo a2enmod webauthn
  - sudo service apache2 restart
  - cd ../hatrac

install:
  - sudo pip3 install .
  - sudo useradd -m -r hatrac
  - sudo -H -u postgres createuser -d hatrac
  - sudo -H -u postgres psql -c "GRANT webauthn TO hatrac"
  - sudo -H -u hatrac createdb hatrac
  - sudo cp test/hatrac_config.json ~hatrac/
  - sudo -H -u hatrac hatrac-deploy admin
  - sudo su -c 'python3 -c "import hatrac as m;m.sample_httpd_config()"' - hatrac > ../wsgi_hatrac.conf
  - sudo cp ../wsgi_hatrac.conf /etc/apache2/conf.d/wsgi_hatrac.conf
  - sudo mkdir /var/www/hatrac
  - sudo chown hatrac /var/www/hatrac

before_script:
  - sudo -H -u webauthn webauthn2-manage adduser test1
  - sudo -H -u webauthn webauthn2-manage passwd test1 dummypassword
  - sudo -H -u webauthn webauthn2-manage addattr admin
  - sudo -H -u webauthn webauthn2-manage assign test1 admin

script:
  - sudo service apache2 restart
  - curl --fail -k -b $COOKIES -c $COOKIES -d username=test1 -d password=dummypassword https://${HOSTNAME}/authn/session
  - bash ./test/rest-smoketest.sh

after_failure:
  - sudo ls -lR /etc/apache2
  - sudo ls -lR /var/run/apache2
  - sudo ls -lR /var/log/apache2
  - sudo cat /etc/apache2/conf.d/webauthn.conf
  - sudo cat /etc/apache2/conf.d/wsgi_webauthn2.conf
  - sudo cat /etc/apache2/conf.d/wsgi_hatrac.conf
  - sudo cat ${HTTPD_ERROR_LOG}
  - sudo systemctl status apache2 -l
