
language: python

sudo: required
dist: trusty

addons:
  postgresq: "9.4"

env:
  global:
    - COOKIES=~/cookies
    - VERBOSE=brief
    - HTTPD_ERROR_LOG=/var/log/apache2/error.log

before_install:
  - sudo apt-get -y update
  - sudo service postgresql stop
  - sudo apt-get -y purge postgresql-9.1 postgresql-9.2 postgresql-9.3
  - sudo apt-get -y install libpq-dev postgresql-server-dev-9.4 python-dev
  - sudo service postgresql start 9.4
  - sudo apt-get -y install apache2 postgresql-9.4 ssl-cert libapache2-mod-wsgi python python-dateutil python-tz
  - sudo apt-get -y purge python-psycopg2
  - sudo pip install web.py
  - sudo pip install psycopg2
  - sudo ln -s /etc/apache2/conf-enabled /etc/apache2/conf.d
  - sudo a2enmod ssl
  - sudo a2ensite default-ssl
  - cd ..
  - git clone https://github.com/informatics-isi-edu/webauthn.git
  - cd webauthn
  - sudo make install
  - sudo make deploy
  - cd ../hatrac

install:
  - sudo python ./setup.py install
  - sudo useradd -m -r hatrac
  - sudo -H -u postgres createuser -d hatrac
  - sudo -H -u postgres psql -c "GRANT webauthn TO hatrac"
  - sudo -H -u hatrac createdb hatrac
  - sudo cp test/hatrac_config.json ~hatrac/
  - sudo -H -u hatrac hatrac-deploy admin
  - sudo cp test/wsgi_hatrac_travis.conf /etc/apache2/conf.d/
  - sudo mkdir /var/www/hatrac
  - sudo chown hatrac /var/www/hatrac
  - sudo service apache2 restart

before_script:
  - sudo -H -u webauthn webauthn2-manage adduser test1
  - sudo -H -u webauthn webauthn2-manage passwd test1 dummypassword
  - sudo -H -u webauthn webauthn2-manage addattr admin
  - sudo -H -u webauthn webauthn2-manage assign test1 admin

script:
  - curl --fail -k -b $COOKIES -c $COOKIES -d username=test1 -d password=dummypassword https://${HOSTNAME}/authn/session
  - bash ./test/rest-smoketest.sh

after_failure:
  - sudo ls -lR /etc/apache2
  - sudo ls -lR /var/run/apache2
  - sudo ls -lR /var/log/apache2
  - sudo cat ${HTTPD_ERROR_LOG}
