site_name: Hatrac Documentation
site_description: Documentation for Hatrac web-service codebase in the DERIVA framework.
site_url: https://informatics-isi-edu.github.io/hatrac/
theme: readthedocs
extra_css: 
  - css/extra.css


pages:
#- Welcome to the documentation: ../README.md
- User Docs:
    - Installing on Red Hat-derived Linux: INSTALL.md
    - Other HOWTO information: HOWTO.md
- Hatrac API and Service Semantics: REST-API.md

markdown_extensions:
    - toc:
        permalink: True
    - admonition:

copyright: Copyright &copy; 2018 <a href="http://github.com/informatics-isi-edu/ermrest">Hatrac Project</a>.

#extra:
#  support: contact@partners.org